#!/bin/bash
#SBATCH --ntasks=1
#SBATCH --mem=14G
#SBATCH -p short
#SBATCH --gres=gpu:1
#SBATCH -t $timelimit
#SBATCH -o $outfile
#SBATCH -e $errfile

module purge
module load Python/3.7.4-GCCcore-8.3.0
module load libs/cuda/10.1.243
module load libs/cudnn/7.6.5.32-CUDA-10.1.243

TMPDIR=/tmp/$${SLURM_JOB_USER}.$${SLURM_JOB_ID}

echo $$TMPDIR

source /trinity/home/kvangarderen/glassimaging/venv/bin/activate
cd /trinity/home/kvangarderen/glassimaging

$copystring

$executestring
