#!/bin/bash
#SBATCH --ntasks=$ntasks
#SBATCH --mem=$mem
#SBATCH --gres=$gres
#SBATCH -t $timelimit
#SBATCH -o $outfile
#SBATCH -e $errfile

# This is the temporary dir for your job on the SSD
# It will be deleted once your job finishes so don't forget to copy your files!
MY_TMP_DIR=/slurmtmp/$${SLURM_JOB_USER}.$${SLURM_JOB_ID}

cd /media/data/kvangarderen/

. /media/data/kvangarderen/python36/bin/activate

cd glassimaging

$copystring

$executestring
